
reserved_words = [
    # Header and Rules
    r'^\d[a-z]{2}CONC$',
    r'^\d[a-z]{2}MAJOR$',
    r'^\d[a-z]{2}MINOR$',
    r'^\d[a-z]{2}COLLEGE$',
    r'^(MAXCLASS)(ES)?$',
    r'^(BLOCK)(S)?$',
    r'^(BLOCKTYPE)(S)?$',
    r'^(CLASS)(ES)?$',
    r'^(COURS)(ES)?$',
    r'^(CREDIT)(S)>$',
    r'^(MINAREA)(S)?$',
    r'^(MINCLASS)(ES)?$',
    r'^(MINCREDIT)(S)?$',
    r'^(SPMAXCREDIT)(S)?$',
    '^(ACCEPT)$',
    '^(ALLBLOCKS)$',
    '^(ALLOW)$',
    # '^AND$',
    # '^+$',
    '^AT$',
    # '^BEGIN$',
    '^(BEGINSUB)$',
    # '^END.$',
    '^(ENDSUB)$',
    '^(EXCEPT)$',
    '^(EXCLUSIVE)$',
    '^(FROM)$',
    '^(GROUP)(S)?$',
    '^(HIDE)-?(RULE)?$',
    '^(HIGH-?PRIORITY)$',
    '^IF$',
    '^IN$',
    '^INCLUDE-BLOCKS-WITH$',
    '^INCLUDING$',
    '^LABEL$',
    '^LASTRES$',
    '^LIBL$',
    '^LOW-?PRIORITY$',
    '^LOWEST-?PRIORITY$',
    '^MAJOR$',
    '^MINSPREAD$',
    '^MINTERM$',
    '^NOCOUNT$',
    '^NONCOURSE$',
    '^NONCOURSES$',
    '^NONEXCLUSIVE$',
    '^NOTGPA$',
    '^NUMBEROFCONCENTRATIONS$',
    '^NUMBEROFMAJORS$',
    '^NUMBEROFMINORS$',
    '^NUMCONCS$',
    '^NUMMAJORS$',
    '^NUMMINORS$',
    '^OPTIONAL$',
    # '^OR$',
    # '^,$',
    '^OTHER$',
    '^PROGRAM$',
    '^PROXY-?ADVICE$',
    '^PSEUDO$',
    '^REMARK$',
    '^RULE-COMPLETE$',
    '^RULE-INCOMPLETE$',
    '^CheckElectiveCreditsAllowed$',
    # '^COLLEGE$',
    '^CONC$',
    '^COPYRULESFROM$',
    '^DECIDE$',
    '^DEGREE$',
    '^DISPLAY$',
    '^DONTSHARE$',
    '^ELSE$',
    r'^MAXCREDIT(S)?$',
    '^MAXPASSFAIL$',
    '^MAXPERDISC$',
    '^MAXSPREAD$',
    '^MAXTERM$',
    '^MAXTRANSFER$',
    '^MINGPA$',
    '^MINGRADE$',
    '^MINOR$',
    '^MINPERDISC$',
    '^MINRES$',
    '^RULETAG$',
    '^SAMEDISC$',
    '^SCHOOL$',
    '^SHAREWITH$',
    '^SPEC$',
    '^SPMAXTERM$',
    '^STANDALONEBLOCK$',
    '^THEN$',
    '^THISBLOCK$',
    '^UNDER$',
    '^WITH'
]

financial_aid_words = [
    '^CompletedTermCount$',
    '^ResidenceCompletedTermCount$',
    '^CreditsAttemptedThisTerm$',
    '^CreditsEarnedThisTerm$',
    '^CreditsAttemptedThisAidYear$',
    '^CreditsEarnedThisAidYear$',
    '^DegreeCreditsRequired$',
    '^LastCompletedTermType$',
    '^Previous$',
    '^Current$',
    '^ResidenceCreditsEarned$',
    '^TotalCreditsAttempted$',
    '^TotalCreditsEarned$',
]
