#! /usr/local/bin/python3
""" Add a requirement block to the quarantine list.
    Get the institution and requirement_id from the TEST_DATA environment variable.
    Get the reason from stdin.
"""

import os
import sys

TEST_DATA = os.getenv('TEST_DATA')
if TEST_DATA is None:
  sys.exit('TEST_DATA not set')

try:
  institution, requirement_id, *_ = TEST_DATA.split('/')[1].split('_')
except ValueError:
  sys.exit(f'{TEST_DATA} is not a valid block string')

with open('./quarantine_list') as ql:
  for line in ql.readlines():
    try:
      i, r, *_ = line.split()
      if i == institution and r == requirement_id:
        sys.exit(f'{institution} {requirement_id} is already quarantined: "{" ".join(_)}"')
    except ValueError as ve:
      pass

reason = input(f'Why quarantine {institution} {requirement_id}? ')
if len(reason) == 0:
  sys.exit('Not quarantined')

with open('./quarantine_list', 'a') as ql:
  print(f'{institution} {requirement_id} {reason}', file=ql)
print(f'Added: {institution} {requirement_id} {reason}')
